### ISSUE TITLE
Timout is never used in the init function

### ISSUE THREAD

**Issue by allilou** [open-inference/python-clients#1]
I'm using this package and I've noticed that the `timeout` parameter is never used in the `__init__` function of the `OpenInferenceClient` class

https://github.com/open-inference/python-clients/blob/16531cd4555c5137081d84cd4d4a585045b18657/packages/open-inference-openapi/generated/open_inference/openapi/client.py#L68

**Comment by zevisert** [comment]
Thanks @allilou, this is generated code but this repo contains functionality to patch the generated code. It looks like you're correct about the timeout not being applied. 

I'm currently on holidays, but will be back next week and I can fix this then!

**Comment by allilou** [comment]
> Thanks @allilou, this is generated code but this repo contains functionality to patch the generated code. It looks like you're correct about the timeout not being applied.
> 
> I'm currently on holidays, but will be back next week and I can fix this then!

Thank's for your response.
I diden't figure out how to patch the generated code.
I will be grateful if you can fix it or tell how can you do that and I will create a pull request with a patch.
Envoy your holiday.

**Comment by zevisert** [comment]
Released as `v2.0.0.1` in 584355ed51cc4218047b7fc5237b78afaccc674e - I want to keep the X.Y.Z version of the clients the same as the spec version for now; which is unchanged here - it remains at `v2.0.0`
 
https://pypi.org/project/open-inference-openapi/2.0.0.1/
